create table if not exists public.madger_discord_members (
  guild_id text not null check (guild_id ~ '^[0-9]{16,22}$'),
  user_id text not null check (user_id ~ '^[0-9]{16,22}$'),
  username text,
  xp bigint not null default 0 check (xp >= 0),
  contribution_points integer not null default 0 check (contribution_points >= 0),
  message_count bigint not null default 0 check (message_count >= 0),
  warning_count integer not null default 0 check (warning_count >= 0),
  verified_at timestamptz,
  last_xp_at timestamptz,
  joined_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (guild_id, user_id)
);

create table if not exists public.madger_discord_events (
  id bigint generated by default as identity primary key,
  guild_id text not null check (guild_id ~ '^[0-9]{16,22}$'),
  user_id text check (user_id is null or user_id ~ '^[0-9]{16,22}$'),
  channel_id text check (channel_id is null or channel_id ~ '^[0-9]{16,22}$'),
  message_id text check (message_id is null or message_id ~ '^[0-9]{16,22}$'),
  event_type text not null check (char_length(event_type) between 2 and 64),
  severity text not null default 'info' check (severity in ('info', 'low', 'medium', 'high', 'critical')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.madger_discord_tickets (
  id bigint generated by default as identity primary key,
  guild_id text not null check (guild_id ~ '^[0-9]{16,22}$'),
  channel_id text not null unique check (channel_id ~ '^[0-9]{16,22}$'),
  owner_user_id text not null check (owner_user_id ~ '^[0-9]{16,22}$'),
  topic text not null check (char_length(topic) between 3 and 200),
  status text not null default 'open' check (status in ('open', 'closed')),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  closed_by text check (closed_by is null or closed_by ~ '^[0-9]{16,22}$')
);

create table if not exists public.madger_discord_submissions (
  id bigint generated by default as identity primary key,
  guild_id text not null check (guild_id ~ '^[0-9]{16,22}$'),
  user_id text not null check (user_id ~ '^[0-9]{16,22}$'),
  mission_code text not null references public.madger_bot_missions(code) on delete restrict,
  evidence_url text not null check (char_length(evidence_url) <= 1000),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewer_user_id text check (reviewer_user_id is null or reviewer_user_id ~ '^[0-9]{16,22}$'),
  review_note text check (char_length(review_note) <= 300),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.madger_discord_settings (
  guild_id text not null check (guild_id ~ '^[0-9]{16,22}$'),
  key text not null check (char_length(key) between 2 and 64),
  value jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (guild_id, key)
);

create index if not exists madger_discord_members_rank_idx on public.madger_discord_members(guild_id, contribution_points desc, xp desc);
create index if not exists madger_discord_events_recent_idx on public.madger_discord_events(guild_id, created_at desc);
create index if not exists madger_discord_events_user_idx on public.madger_discord_events(guild_id, user_id, created_at desc) where user_id is not null;
create index if not exists madger_discord_submissions_mission_idx on public.madger_discord_submissions(mission_code);
create index if not exists madger_discord_submissions_pending_idx on public.madger_discord_submissions(guild_id, created_at) where status = 'pending';

alter table public.madger_discord_members enable row level security;
alter table public.madger_discord_events enable row level security;
alter table public.madger_discord_tickets enable row level security;
alter table public.madger_discord_submissions enable row level security;
alter table public.madger_discord_settings enable row level security;

revoke all on public.madger_discord_members, public.madger_discord_events,
  public.madger_discord_tickets, public.madger_discord_submissions,
  public.madger_discord_settings from public, anon, authenticated;
grant select, insert, update, delete on public.madger_discord_members,
  public.madger_discord_events, public.madger_discord_tickets,
  public.madger_discord_submissions, public.madger_discord_settings to service_role;
grant usage, select on sequence public.madger_discord_events_id_seq,
  public.madger_discord_tickets_id_seq, public.madger_discord_submissions_id_seq to service_role;

create or replace function public.madger_discord_review_submission(
  p_submission_id bigint,
  p_status text,
  p_reviewer_user_id text,
  p_note text default null
) returns public.madger_discord_submissions
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_submission public.madger_discord_submissions%rowtype;
  v_points integer;
begin
  if p_status not in ('approved', 'rejected') then raise exception 'invalid status'; end if;
  select * into v_submission from public.madger_discord_submissions where id = p_submission_id for update;
  if not found then raise exception 'submission not found'; end if;
  if v_submission.status <> 'pending' then raise exception 'submission already reviewed'; end if;
  if p_status = 'approved' then
    select points into v_points from public.madger_bot_missions where code = v_submission.mission_code;
    insert into public.madger_discord_members(guild_id, user_id, contribution_points)
      values (v_submission.guild_id, v_submission.user_id, coalesce(v_points, 0))
      on conflict (guild_id, user_id) do update
      set contribution_points = public.madger_discord_members.contribution_points + excluded.contribution_points,
          updated_at = now();
  end if;
  update public.madger_discord_submissions
    set status = p_status, reviewer_user_id = p_reviewer_user_id,
        review_note = nullif(left(coalesce(p_note, ''), 300), ''), reviewed_at = now()
    where id = p_submission_id returning * into v_submission;
  return v_submission;
end;
$$;

revoke all on function public.madger_discord_review_submission(bigint, text, text, text) from public, anon, authenticated;
grant execute on function public.madger_discord_review_submission(bigint, text, text, text) to service_role;
